language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t karanjain71/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true karanjain71/docker-react npm run test