version: '3'
services:
  web:
    build:
      context: .
      # Where should it pick its files from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app